import { createFileRoute } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { gridQuery, sitesQuery } from "@/lib/queries";
import { AppShell, Card, DistributionBar, PageHeader, Stat } from "@/components/AppShell";
import { distribution, fmt, URBAN_COLORS, COVERAGE_COLORS, DEMAND_COLORS } from "@/lib/telco-data";

export const Route = createFileRoute("/agents")({
  head: () => ({ meta: [{ title: "Agents · 5G Planner" }] }),
  loader: ({ context }) => {
    context.queryClient.ensureQueryData(gridQuery);
    context.queryClient.ensureQueryData(sitesQuery);
  },
  component: Page,
});

function mean<T>(arr: T[], pick: (x: T) => number): number {
  if (!arr.length) return 0;
  return arr.reduce((a, b) => a + pick(b), 0) / arr.length;
}
function sum<T>(arr: T[], pick: (x: T) => number): number {
  return arr.reduce((a, b) => a + pick(b), 0);
}

function Page() {
  const { data: grid } = useSuspenseQuery(gridQuery);
  const { data: sites } = useSuspenseQuery(sitesQuery);
  const p = grid.features.map((f) => f.properties);

  return (
    <AppShell>
      <div className="mx-auto max-w-[1600px] px-6 py-8 space-y-8">
        <PageHeader
          title="Agents"
          subtitle="Indicators generated by the real agents (OSMnx · PopulationDemand · Terrain · Coverage · SitePlacement)."
        />

        {/* OSMNX */}
        <section>
          <h2 className="text-sm uppercase tracking-wider text-muted-foreground mb-3">OSMnxUrbanAgent</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3">
            <Stat label="Total buildings" value={fmt(sum(p, (x) => x.n_buildings), 0)} />
            <Stat label="Mean height" value={fmt(mean(p, (x) => x.estimated_height_m), 1)} unit="m" />
            <Stat label="Urban intensity (μ)" value={fmt(mean(p, (x) => x.urban_intensity), 3)} />
            <Stat label="Obstruction (μ)" value={fmt(mean(p, (x) => x.obstruction_index), 3)} />
            <Stat label="Propagation complexity" value={fmt(mean(p, (x) => x.propagation_complexity), 3)} />
            <Stat label="Handover risk" value={fmt(mean(p, (x) => x.handover_risk), 3)} />
            <Stat label="Compactness" value={fmt(mean(p, (x) => x.urban_compactness), 3)} />
            <Stat label="Accessibility (μ)" value={fmt(mean(p, (x) => x.accessibility_score), 3)} />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Card title="Urban class"><DistributionBar items={distribution(grid, "urban_class")} colors={URBAN_COLORS} /></Card>
            <Card title="Urban structure"><DistributionBar items={distribution(grid, "urban_structure")} /></Card>
            <Card title="Accessibility class"><DistributionBar items={distribution(grid, "accessibility_class")} /></Card>
          </div>
        </section>

        {/* DEMAND */}
        <section>
          <h2 className="text-sm uppercase tracking-wider text-muted-foreground mb-3">PopulationDemandAgent</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3">
            <Stat label="Population" value={fmt(sum(p, (x) => x.population), 0)} />
            <Stat label="Density (μ)" value={fmt(mean(p, (x) => x.population_density), 0)} unit="hab/km²" />
            <Stat label="Base demand" value={fmt(sum(p, (x) => x.base_demand_gbps), 2)} unit="Gbps" />
            <Stat label="Peak demand" value={fmt(sum(p, (x) => x.peak_demand_gbps), 2)} unit="Gbps" />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            <Card title="Usage type"><DistributionBar items={distribution(grid, "usage_type")} /></Card>
            <Card title="Demand class"><DistributionBar items={distribution(grid, "demand_class")} colors={DEMAND_COLORS} /></Card>
            <Card title="Demand category"><DistributionBar items={distribution(grid, "demand_category")} colors={DEMAND_COLORS} /></Card>
          </div>
        </section>

        {/* TERRAIN */}
        <section>
          <h2 className="text-sm uppercase tracking-wider text-muted-foreground mb-3">TerrainEnvironmentAgent</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3">
            <Stat label="Elevation (μ)" value={fmt(mean(p, (x) => x.elevation_mean), 1)} unit="m" />
            <Stat label="Elevation range" value={fmt(mean(p, (x) => x.elevation_range), 1)} unit="m" />
            <Stat label="Slope norm (μ)" value={fmt(mean(p, (x) => x.slope_norm), 3)} />
            <Stat label="LOS probability" value={`${(mean(p, (x) => x.los_probability) * 100).toFixed(1)}%`} />
            <Stat label="Attenuation (μ)" value={fmt(mean(p, (x) => x.attenuation_factor), 1)} unit="dB" />
            <Stat label="Forest ratio" value={`${(mean(p, (x) => x.forest_ratio) * 100).toFixed(1)}%`} />
            <Stat label="Water ratio" value={`${(mean(p, (x) => x.water_ratio) * 100).toFixed(1)}%`} />
            <Stat label="Terrain complexity" value={fmt(mean(p, (x) => x.terrain_complexity), 3)} />
          </div>
        </section>

        {/* COVERAGE */}
        <section>
          <h2 className="text-sm uppercase tracking-wider text-muted-foreground mb-3">CoverageAgent</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3">
            <Stat label="Antennas" value={fmt(sum(p, (x) => x.antenna_count), 0)} />
            <Stat label="NR (5G)" value={fmt(sum(p, (x) => x.antenna_count_nr), 0)} />
            <Stat label="LTE" value={fmt(sum(p, (x) => x.antenna_count_lte), 0)} />
            <Stat label="Capacity total" value={fmt(sum(p, (x) => x.capacity_available_gbps), 2)} unit="Gbps" />
            <Stat label="Deficit total" value={fmt(sum(p, (x) => x.capacity_deficit_gbps), 2)} unit="Gbps" tone="bad" />
            <Stat label="Coverage score (μ)" value={fmt(mean(p, (x) => x.coverage_score), 3)} />
            <Stat label="Overload score (μ)" value={fmt(mean(p, (x) => x.overload_score), 3)} />
            <Stat label="Hotspot risk cells" value={fmt(p.filter((x) => x.is_hotspot_risk).length, 0)} tone="warn" />
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <Card title="Coverage class"><DistributionBar items={distribution(grid, "coverage_class")} colors={COVERAGE_COLORS} /></Card>
            <Card title="Nearest radio"><DistributionBar items={distribution(grid, "nearest_radio")} /></Card>
          </div>
        </section>

        {/* SITES */}
        <section>
          <h2 className="text-sm uppercase tracking-wider text-muted-foreground mb-3">SitePlacementAgent</h2>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-3 mb-3">
            <Stat label="Sites recommended" value={sites.features.length} tone="good" />
            <Stat
              label="Mean composite score"
              value={fmt(mean(sites.features, (f) => f.properties.composite_score), 4)}
            />
            <Stat
              label="Max score"
              value={fmt(Math.max(...sites.features.map((f) => f.properties.composite_score)), 4)}
            />
            <Stat
              label="Total deficit addressed"
              value={fmt(sum(sites.features, (f) => f.properties.capacity_deficit_gbps), 2)}
              unit="Gbps"
            />
          </div>
        </section>
      </div>
    </AppShell>
  );
}
